# Generated by Django 4.1 on 2023-08-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArticleInfo",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.IntegerField(verbose_name="置顶")),
                ("title", models.CharField(max_length=32, verbose_name="标题")),
                ("commentCounts", models.IntegerField(verbose_name="评论量")),
                ("viewCounts", models.IntegerField(verbose_name="浏览量")),
                ("summary", models.CharField(max_length=100, verbose_name="摘要")),
                ("author", models.CharField(max_length=16, verbose_name="作者")),
                ("tag", models.JSONField(verbose_name="标签")),
                ("createDate", models.DateField(verbose_name="日期")),
            ],
        ),
    ]
