# Generated by Django 4.1 on 2023-08-03 07:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myblog_django_app", "0002_alter_articleinfo_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articleinfo",
            name="tag",
        ),
    ]
