# Generated by Django 4.1 on 2023-08-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myblog_django_app", "0004_articleinfo_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleinfo",
            name="img",
            field=models.ImageField(
                default="myblog_django/media/ArticlePhotos/default.png",
                upload_to="ArticlePhotos",
                verbose_name="图像",
            ),
        ),
    ]
