# Generated by Django 4.1 on 2023-08-03 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("myblog_django_app", "0005_alter_articleinfo_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticlePost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.IntegerField(verbose_name="置顶")),
                ("author", models.CharField(max_length=16, verbose_name="作者")),
                ("title", models.CharField(max_length=100)),
                (
                    "img",
                    models.ImageField(
                        default="myblog_django/media/ArticlePhotos/default.png",
                        upload_to="ArticlePhotos",
                        verbose_name="图像",
                    ),
                ),
                ("body", models.TextField()),
                ("summary", models.CharField(max_length=100, verbose_name="摘要")),
                ("commentCounts", models.IntegerField(verbose_name="评论量")),
                ("viewCounts", models.IntegerField(verbose_name="浏览量")),
                ("createDate", models.DateTimeField(default=django.utils.timezone.now)),
                ("updateDate", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-createDate",),
            },
        ),
        migrations.DeleteModel(
            name="ArticleInfo",
        ),
    ]
