# Generated by Django 4.1 on 2023-08-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myblog_django_app", "0007_alter_articlepost_createdate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepost",
            name="commentCounts",
            field=models.IntegerField(default=0, verbose_name="评论量"),
        ),
        migrations.AlterField(
            model_name="articlepost",
            name="viewCounts",
            field=models.IntegerField(default=0, verbose_name="浏览量"),
        ),
    ]
