# Generated by Django 4.1 on 2023-08-03 08:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myblog_django_app", "0008_alter_articlepost_commentcounts_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ArticlePost",
            new_name="ArticleInfo",
        ),
    ]
