# Generated by Django 4.1 on 2023-08-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "myblog_django_app",
            "0010_alter_articleinfo_body_alter_articleinfo_createdate_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articleinfo",
            options={"ordering": ("-weight", "-createDate")},
        ),
        migrations.AlterField(
            model_name="articleinfo",
            name="weight",
            field=models.IntegerField(default=0, verbose_name="置顶"),
        ),
    ]
