# Generated by Django 4.1 on 2023-08-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "myblog_django_app",
            "0011_alter_articleinfo_options_alter_articleinfo_weight",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="articleinfo",
            name="tags",
            field=models.TextField(
                blank=True, help_text="用逗号分隔", null=True, verbose_name="标签"
            ),
        ),
    ]
