# Generated by Django 4.1 on 2023-08-04 11:37

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):
    dependencies = [
        ("myblog_django_app", "0012_articleinfo_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleinfo",
            name="body",
            field=mdeditor.fields.MDTextField(verbose_name="内容"),
        ),
    ]
