# Generated by Django 4.1 on 2023-08-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myblog_django_app", "0013_alter_articleinfo_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=32, verbose_name="邮箱")),
                ("password", models.CharField(max_length=32, verbose_name="密码")),
                ("name", models.CharField(max_length=32, verbose_name="昵称")),
                ("website", models.CharField(max_length=128, verbose_name="个人网址")),
                ("motto", models.CharField(max_length=128, verbose_name="个性签名")),
            ],
        ),
    ]
