# Generated by Django 4.1 on 2023-08-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myblog_django_app", "0014_userinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="avatar",
            field=models.ImageField(
                default="myblog_django/media/PersonalPhotos/avatar.jpg",
                upload_to="PersonalPhotos",
                verbose_name="头像",
            ),
        ),
    ]
