# Generated by Django 4.1 on 2023-08-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myblog_django_app", "0015_userinfo_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("top", models.IntegerField(verbose_name="顶距")),
                ("content", models.CharField(max_length=1024, verbose_name="内容")),
            ],
        ),
    ]
