# Generated by Django 4.1 on 2023-08-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myblog_django_app", "0016_messageinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messageinfo",
            name="top",
            field=models.CharField(max_length=16, verbose_name="顶距"),
        ),
    ]
