# Generated by Django 4.1 on 2023-08-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myblog_django_app", "0017_alter_messageinfo_top"),
    ]

    operations = [
        migrations.AddField(
            model_name="messageinfo",
            name="right",
            field=models.CharField(max_length=16, null=True, verbose_name="右距"),
        ),
    ]
