# Generated by Django 4.1 on 2023-08-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myblog_django_app", "0018_messageinfo_right"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleinfo",
            name="img",
            field=models.ImageField(
                default="ArticlePhotos/default.png",
                upload_to="ArticlePhotos",
                verbose_name="图像",
            ),
        ),
    ]
