# Generated by Django 4.1 on 2023-08-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myblog_django_app", "0019_alter_articleinfo_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="FriendsInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("friend", models.CharField(max_length=256, verbose_name="友链")),
            ],
        ),
        migrations.CreateModel(
            name="ImgOfPostInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("postid", models.IntegerField(verbose_name="博客ID")),
                (
                    "img",
                    models.ImageField(
                        default="PostPhotos/default.png",
                        upload_to="PostPhotos",
                        verbose_name="图片",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        default="Avatars/default.png",
                        upload_to="Avatars",
                        verbose_name="头像",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="昵称")),
                ("content", models.TextField(blank=True, null=True, verbose_name="内容")),
                (
                    "createTime",
                    models.TimeField(default="2023-08-31 16:34", verbose_name="时间"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="articleinfo",
            name="img",
            field=models.ImageField(
                default="ArticlePhotos/default.png",
                upload_to="ArticlePhotos",
                verbose_name="图片",
            ),
        ),
    ]
