# Generated by Django 4.1 on 2023-08-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myblog_django_app", "0020_friendsinfo_imgofpostinfo_postinfo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postinfo",
            name="createTime",
            field=models.DateTimeField(default="2023-08-31 20:30", verbose_name="时间"),
        ),
    ]
