# Generated by Django 4.1 on 2023-08-31 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myblog_django_app", "0021_alter_postinfo_createtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postinfo",
            name="createTime",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 31, 20, 37, 17, 392734),
                verbose_name="时间",
            ),
        ),
    ]
