# Generated by Django 4.1 on 2023-08-31 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myblog_django_app", "0022_alter_postinfo_createtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postinfo",
            name="avatar",
            field=models.ImageField(
                default="Avatars/default.jpg", upload_to="Avatars", verbose_name="头像"
            ),
        ),
        migrations.AlterField(
            model_name="postinfo",
            name="createTime",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 31, 20, 51, 33, 632584),
                verbose_name="时间",
            ),
        ),
    ]
