# Generated by Django 4.1 on 2023-08-31 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myblog_django_app", "0023_alter_postinfo_avatar_alter_postinfo_createtime"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postinfo",
            options={"ordering": ("-createTime",)},
        ),
        migrations.AlterField(
            model_name="postinfo",
            name="createTime",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 31, 22, 35, 54, 258129),
                verbose_name="时间",
            ),
        ),
    ]
