# Generated by Django 4.1 on 2023-08-31 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myblog_django_app", "0024_alter_postinfo_options_alter_postinfo_createtime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="friendsinfo",
            name="friend",
        ),
        migrations.AddField(
            model_name="friendsinfo",
            name="link",
            field=models.CharField(max_length=256, null=True, verbose_name="链接"),
        ),
        migrations.AddField(
            model_name="friendsinfo",
            name="name",
            field=models.CharField(max_length=32, null=True, verbose_name="名称"),
        ),
        migrations.AlterField(
            model_name="postinfo",
            name="createTime",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 1, 0, 36, 30, 211930),
                verbose_name="时间",
            ),
        ),
    ]
