# Generated by Django 4.1 on 2023-09-03 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "myblog_django_app",
            "0025_remove_friendsinfo_friend_friendsinfo_link_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="friendsinfo",
            name="img",
            field=models.ImageField(
                default="FriendsPhotos/default.png",
                upload_to="FriendsPhotos",
                verbose_name="图片",
            ),
        ),
        migrations.AddField(
            model_name="friendsinfo",
            name="intro",
            field=models.CharField(max_length=128, null=True, verbose_name="介绍"),
        ),
        migrations.AlterField(
            model_name="postinfo",
            name="createTime",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 3, 20, 31, 54, 587408),
                verbose_name="时间",
            ),
        ),
    ]
