# Generated by Django 4.1 on 2023-09-04 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myblog_django_app", "0027_alter_postinfo_createtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postinfo",
            name="createTime",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 4, 14, 6, 23, 434448),
                verbose_name="时间",
            ),
        ),
    ]
