# Generated by Django 4.1 on 2023-09-04 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myblog_django_app", "0028_alter_postinfo_createtime"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("articleid", models.IntegerField(verbose_name="文章id")),
                ("content", models.CharField(max_length=1024, verbose_name="内容")),
                (
                    "createTime",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 9, 4, 15, 23, 18, 941080),
                        verbose_name="时间",
                    ),
                ),
            ],
            options={
                "ordering": ("-createTime",),
            },
        ),
        migrations.AlterField(
            model_name="postinfo",
            name="createTime",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 4, 15, 23, 18, 941080),
                verbose_name="时间",
            ),
        ),
    ]
