# Generated by Django 4.1 on 2023-09-04 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myblog_django_app", "0029_commentinfo_alter_postinfo_createtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentinfo",
            name="createTime",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 4, 8, 8, 21, 153782, tzinfo=datetime.timezone.utc
                ),
                verbose_name="时间",
            ),
        ),
        migrations.AlterField(
            model_name="postinfo",
            name="createTime",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 4, 8, 8, 21, 152219, tzinfo=datetime.timezone.utc
                ),
                verbose_name="时间",
            ),
        ),
    ]
