# Generated by Django 4.2.5 on 2023-09-06 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myblog_django_app", "0031_alter_commentinfo_createtime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleinfo",
            name="img_data",
            field=models.BinaryField(blank=True, null=True, verbose_name="文件数据"),
        ),
        migrations.AlterField(
            model_name="commentinfo",
            name="createTime",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 6, 17, 58, 38, 37984),
                verbose_name="时间",
            ),
        ),
        migrations.AlterField(
            model_name="postinfo",
            name="createTime",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 6, 17, 58, 38, 37984),
                verbose_name="时间",
            ),
        ),
    ]
